yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  apollo-server@2.16.0:
    peerDependencies:
      "@types/express": ^4.17.6
  apollo-engine-reporting-protobuf@*:
    dependencies:
      "@types/long": "*"
  subscriptions-transport-ws@*:
    dependencies:
      "@types/ws": "*"
  "@apollographql/apollo-tools@*":
    dependencies:
      graphql: ^14.3
