packageExtensions:
  "@apollographql/apollo-tools@*":
    dependencies:
      graphql: ^14.3
  apollo-engine-reporting-protobuf@*:
    dependencies:
      "@types/long": "*"
  apollo-server@2.16.0:
    peerDependencies:
      "@types/express": ^4.17.6
  relay-compiler@10.0.1:
    peerDependencies:
      graphql: ^14.0.0 || ^15.0.0
  subscriptions-transport-ws@*:
    dependencies:
      "@types/ws": "*"

yarnPath: .yarn/releases/yarn-1.22.1.cjs
