version: "3.5"
services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma_password
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data